version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aries
      POSTGRES_DB: hacktiv8
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - example-network

  api:
    container_name: go_crud
    image: "mongol2/gocrud"
    build: .
    restart: on-failure
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=aries
      - DB_NAME=hacktiv8
      - JWT_SECRET=4121353k0pr453ty0
    ports:
      - 3000:3000
    networks:
      - example-network

networks:
  example-network:
volumes:
  postgres-data:
